---
title: "QC plots"
author: "Xueyi Dong"
date: "21/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(ggplot2)
setwd("~/analysis/smchd1/long/run2/QC")
```

```{r}
rep1 <- read_tsv("NanoRResult/rep1/Exp/metadata.txt")
rep2 <- read_tsv("NanoRResult/rep2/Exp/metadata.txt")
qcdata <- rbind(rep1, rep2)
```

Length distribution without cutoff

```{r}
pdf("length.pdf", height = 5)
ggplot(qcdata, aes(x = `Length of Read` )) +
  geom_density() +
  theme_bw()
dev.off()
```


calculate 0.99 quantile of read length

```{r}
cutoff <- quantile(qcdata$`Length of Read`, 0.99)
cutoff
```

length vs quality

```{r}
pdf("lengthquality.pdf")
ggplot(qcdata, aes(x = `Length of Read`, y = Quality)) +
  geom_point() +
  xlim(NA, cutoff)
dev.off()
```

length vs pass/fail

```{r}
pdf("lengthpassfail.pdf")
qcdata$pass <- qcdata$Quality > 7
ggplot(qcdata, aes(x = `Length of Read`, fill = pass)) +
  geom_density(alpha = 0.4) +
  xlim(NA, cutoff) +
  theme_bw()
dev.off()
```

length vs quality, box plot
```{r}
qcdata$length <- "medium"
qcdata$length[qcdata$`Length of Read` < quantile(qcdata$`Length of Read`, 1/3)] <- "short"
qcdata$length[qcdata$`Length of Read` > quantile(qcdata$`Length of Read`, 2/3)] <- "long"
qcdata$length[qcdata$`Length of Read` > quantile(qcdata$`Length of Read`, 0.95)] <- "extra long"
pdf("lengthqualityviolin.pdf")
ggplot(qcdata, aes(x = length, y = Quality, fill = length, colour = length)) +
  geom_violin(alpha = 0.4) +
  theme_bw()
dev.off()
```

