source("Soneson/func.R")
library(ShortRead)
library(GenomicAlignments)
library(dplyr)
library(ggplot2)
library(data.table)
library(GenomicFeatures)
library(Hmisc)

bam <- "../flames/results/realign2transcript.bam"

# for (i in 1:8){
#   cat("Reading", bams[i], "\n")
#   bam1 <- suppressWarnings(readBam(file.path(dir_bam, bams[i])))
#   cat("Making read DF\n")
#   readDF <- makeReadDf(bam1)
#   cat("Making summary list\n")
#   summ <- makeSummaryList(bam1)
#   saveRDS(readDF, file = file.path(dir_bam, paste0(bams[i], ".readDF.RDS")))
#   saveRDS(summ, file=file.path(dir_bam, paste0(bams[i], ".summ.RDS")))
# }
cat("Reading bam file.\n")
bam1 <- suppressWarnings(readBam(bam))
cat("Making read DF.\n")
readDF <- makeReadDf(bam1)
cat("Making summary list.\n")
summ <- makeSummaryList(bam1)
cat("Saving readDF.\n")
saveRDS(readDF, "../flames/results/readDF.RDS")
cat("Saving summary list.\n")
saveRDS(summ, "../flames/results/summList.RDS")
