---
title: "QC plots"
author: "Xueyi Dong"
date: "21/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
```

```{r}
qcdata <- readRDS("./summaryInfo.RDS")
```

Length distribution without cutoff

```{r}
pdf("length.pdf", height = 5)
ggplot(qcdata, aes(x = `Length of Read` )) +
  geom_density() +
  theme_bw() +
  coord_trans(x = "log10")
dev.off()
```


calculate 0.99 quantile of read length

```{r}
cutoff <- quantile(qcdata$`Length of Read`, 0.99)
cutoff
```

length vs quality (file too big, abandon)

```{r}
# pdf("lengthquality.pdf", )
# ggplot(qcdata, aes(x = `Length of Read`, y = Quality)) +
#   geom_point() +
#   xlim(NA, cutoff)
# dev.off()
```

length vs pass/fail

```{r}
pdf("lengthpassfail.pdf", height = 4, width = 8)
qcdata$pass <- qcdata$Quality > 7
ggplot(qcdata, aes(x = `Length of Read`, fill = pass)) +
  geom_density(alpha = 0.4) +
  xlim(NA, cutoff) +
  theme_bw()
dev.off()
```

length vs quality, box plot


```{r}
quantile(qcdata$`Length of Read`, 1/3)
quantile(qcdata$`Length of Read`, 2/3)
quantile(qcdata$`Length of Read`, 0.95)
```

```{r}
qcdata$length <- "medium"
qcdata$length[qcdata$`Length of Read` < quantile(qcdata$`Length of Read`, 1/3)] <- "short"
qcdata$length[qcdata$`Length of Read` > quantile(qcdata$`Length of Read`, 2/3)] <- "long"
qcdata$length[qcdata$`Length of Read` > quantile(qcdata$`Length of Read`, 0.95)] <- "extra long"
pdf("lengthqualityviolin.pdf", height = 4, width = 8)
ggplot(qcdata, aes(x = length, y = Quality, fill = length, colour = length)) +
  geom_violin(alpha = 0.4) +
  theme_bw() +
  theme(text = element_text(size=20))
dev.off()
```

```{r}
maxLength = max(qcdata$`Length of Read`)
qcdata$LengthGroup <- Hmisc::cut2(qcdata$`Length of Read`, cuts = c(0, 500, 1000,
                                                     3000, maxLength))
qcdata$LengthGroup <- gsub(" ", "", qcdata$LengthGroup)
qcdata$LengthGroup <- gsub(",", ", ", qcdata$LengthGroup)

qcdata$LengthGroup <- factor(qcdata$LengthGroup, levels = c(
  "[0, 500)", "[500, 1000)", "[1000, 3000)", "[3000, 1823562]"
))

pdf("lengthqualityviolin.pdf", height = 4, width = 8)
ggplot(qcdata, aes(x=LengthGroup, y=Quality, fill=LengthGroup, colour = LengthGroup)) +
  geom_violin(alpha = 0.4) +
  theme_bw() +
  theme(text = element_text(size=20), legend.position = "none") +
  labs(x = "Read length")
dev.off()
```

